/**
 * Evidence quarantine — types and the outbox contract.
 *
 * Quarantine is an OPERATIONAL SECURITY workflow, not lifecycle governance. When the
 * malware-scan ingestion gate blocks an upload, the platform records sanitized metadata
 * about the rejected payload and emits an outbox event for downstream security operations.
 *
 * These types are NSO-generic (no sport-specific fields) and carry only sanitized metadata:
 *  - NEVER the raw payload bytes;
 *  - NEVER bearer tokens, connection strings, or full request headers;
 *  - only a generic `threatName` (never the matched signature contents) and a content hash.
 */

/**
 * Scan outcomes that can lead to quarantine. This is exactly the set of non-`clean`
 * {@link EvidenceScanStatus} values that block an upload (`infected`, or `error`/`skipped`
 * when scanning is required).
 */
export type QuarantineScanStatus = 'infected' | 'error' | 'skipped';

/**
 * Operational lifecycle of a quarantine event itself (NOT a governed lifecycle state and NOT
 * an FSM state). v1 only ever records `recorded`; the later values are reserved for a future
 * security-review/release pass and are constrained by the DB CHECK only.
 */
export type QuarantineStatus = 'recorded' | 'notified' | 'reviewed' | 'released' | 'discarded';

/** Outbox message type emitted when a quarantine event is recorded. */
export const EVIDENCE_QUARANTINE_RECORDED_MESSAGE_TYPE = 'evidence.quarantine.recorded';

/**
 * Sanitized metadata describing a blocked/suspicious upload. NEVER includes raw payload
 * bytes. The `quarantineEventId` is generated by the service so the stored row id and the
 * outbox dedupe key are stable and correlated.
 */
export interface EvidenceQuarantineRecord {
  readonly quarantineEventId: string;
  readonly tenantId: string;
  /** Caller-intended governance evidence object id, when one was supplied. */
  readonly evidenceObjectId?: string;
  readonly sourceFilename?: string;
  readonly contentType: string;
  readonly sizeBytes: number;
  /** SHA-256 hex digest of the rejected payload (no bytes are retained). */
  readonly contentHash: string;
  readonly scanStatus: QuarantineScanStatus;
  readonly scanner: string;
  readonly signatureVersion?: string;
  /** Generic threat name (never the matched signature contents). */
  readonly threatName?: string;
  readonly reason?: string;
  readonly uploadActorUserId?: string;
  readonly requestId?: string;
  readonly correlationId?: string;
}

/** Identifiers returned after a quarantine event (and its outbox message) are persisted. */
export interface RecordedQuarantineEvent {
  readonly quarantineEventId: string;
  /** Outbox message id enqueued in the same write (transactional outbox). */
  readonly outboxMessageId: string;
}

/**
 * Sanitized outbox payload for a recorded quarantine event. Carries only NSO-generic, non
 * secret routing/observability metadata — NEVER raw bytes, tokens, headers, or the matched
 * signature contents.
 */
export interface EvidenceQuarantineRecordedPayload {
  readonly quarantineEventId: string;
  readonly tenantId: string;
  readonly evidenceObjectId?: string;
  readonly contentHash: string;
  readonly contentType: string;
  readonly sizeBytes: number;
  readonly scanStatus: QuarantineScanStatus;
  readonly scanner: string;
  readonly threatName?: string;
  readonly requestId?: string;
  readonly correlationId?: string;
}

/**
 * Normalize an arbitrary scan status into a {@link QuarantineScanStatus}. A `clean` or
 * unknown status is never expected on a blocked upload; it collapses to `error` so the DB
 * CHECK constraint always holds (fail-safe).
 */
export function toQuarantineScanStatus(status: string): QuarantineScanStatus {
  return status === 'infected' || status === 'error' || status === 'skipped' ? status : 'error';
}
